title: "MRMS Rainfall Measurements"
description: >
  MRMS Rainfall Measurements, converted to Zarr format. All are the hourly accumulations. A few different options are included, including the Gauge measurement, MultiSensor MultiPass measurement, and the derived precipitation rate.
recipes:
  - id: "mrms"
provenance:
  providers:
    - name: "Jacob Bieker"
      roles:
        - producer
      url: "https://source.coop/bkr"
    - name: "Source.Coop"
      roles:
        - host
      url: "https://source.coop"
  license: "unknown"
maintainers:
  - name: "Julius Busecke"
    orcid: "0000-0001-8571-865X"
    github: jbusecke
